[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[sources]
MultiScaleTreeGraph = {path = ".."}