name = "MTG"
uuid = "dd4a991b-8a45-4075-bede-262ee62d5583"
authors = ["remi.vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MutableNamedTuples = "af6c499f-54b4-48cc-bbd2-094bba7533c7"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
AbstractTrees = "0.3"
DataFrames = "0.21, 0.22"
MutableNamedTuples = "0.1"
OrderedCollections = "1.4"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
